### ISSUE TITLE
Оптимизируйте циклы

### ISSUE THREAD

**Issue by spogozhev** [HanBinGer/Computer_Practice_2021#3]
https://github.com/HanBinGer/Computer_Practice_2021/blob/bf4de5f08494e5ef8f6b1f130863c1f5be4d294c/Homework/4/rhombuses_from_asterisks_Mk2.cpp#L13

В таких циклах следует в другую сторону идти, чтобы на  каждом шаге не вычислять сложное условие.
  for (int i = (2*n-1); i >=1 ;-- i)

**Comment by HanBinGer** [comment]
решил не трогать порядок, просто ввел переменную (можно константную, но думаю излишне)
