### ISSUE TITLE
Сдвиг в противоположную сторону не работает

### ISSUE THREAD

**Issue by spogozhev** [HanBinGer/Computer_Practice_2021#4]
https://github.com/HanBinGer/Computer_Practice_2021/blob/122d9f88bc82c52fcc1ac8bc99dd1a4c1e048459/Homework/2021.11.08/shift_array.cpp#L16

А что, если shift отрицательное число будет?

**Comment by HanBinGer** [comment]
Добавил поддержку отрицательных чисел
